#!/usr/bin/env python3
"""Set up the Remotion template project for rendering from segments JSON.

Generates src/data.ts and src/Root.tsx in-place in the template directory,
then copies media assets (audio + images) into public/.
The template directory with pre-installed node_modules is reused across renders.
"""

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

STEPS_DIR = Path(__file__).parent
TEMPLATE_DIR = STEPS_DIR / "remotion_template"

ASPECT_MAP = {
    "9:16": (1080, 1920),
    "16:9": (1920, 1080),
    "1:1": (1080, 1080),
    "4:3": (1440, 1080),
    "3:4": (1080, 1440),
}

BACKGROUNDS = [
    "linear-gradient(180deg, #111111 0%, #1b1b1b 52%, #080808 100%)",
    "linear-gradient(180deg, #101417 0%, #1b2024 52%, #090b0d 100%)",
    "linear-gradient(180deg, #15120f 0%, #211d18 52%, #0b0a08 100%)",
]

ROOT_TSX = """import { Composition } from "remotion";
import { MainScene } from "./Main";
import { CONFIG, SEGMENTS } from "./data";

export const RemotionRoot: React.FC = () => {
  const durationInFrames = SEGMENTS.reduce((sum, seg) => sum + seg.duration_frames, 0);

  return (
    <>
      <Composition
        id="MainScene"
        component={MainScene}
        durationInFrames={durationInFrames}
        fps={CONFIG.fps}
        width={CONFIG.width}
        height={CONFIG.height}
      />
    </>
  );
};
"""


def aspect_dims(aspect: str) -> tuple[int, int]:
    if aspect in ASPECT_MAP:
        return ASPECT_MAP[aspect]
    try:
        w, h = aspect.split(":")
        return int(w) * 100, int(h) * 100
    except (ValueError, AttributeError):
        return 1080, 1920


def sanitize_filename(path: str) -> str:
    if not path:
        return ""
    return Path(path).name


def to_native_path(path: str) -> Path:
    """Convert bash-style /d/... paths to Windows D:\\... if needed."""
    p = Path(path)
    if p.exists():
        return p
    # On Windows, /d/foo → D:\\foo
    if path and len(path) > 2 and path[0] == "/" and path[2] == "/":
        drive = path[1].upper() + ":"
        rest = path[2:]
        native = Path(drive + rest)
        if native.exists():
            return native
    return p


def build_data_ts(
    segments: list[dict],
    topic: str,
    aspect: str,
    seg_dur: float,
    fps: int,
) -> str:
    width, height = aspect_dims(aspect)

    slim_segments = []
    for seg in segments:
        duration_seconds = float(seg.get("duration_est") or seg.get("audio_duration") or seg_dur)
        duration_seconds = max(3.0, duration_seconds)
        caption_chunks = seg.get("caption_chunks") or [seg.get("narration", "")]
        slim_segments.append({
            "narration": seg.get("narration", ""),
            "title": seg.get("title", ""),
            "summary": seg.get("summary", ""),
            "source_label": seg.get("source_label", ""),
            "heat_label": seg.get("heat_label", ""),
            "category": seg.get("category", ""),
            "score": seg.get("score", ""),
            "comments": seg.get("comments", ""),
            "duration_seconds": round(duration_seconds, 2),
            "duration_frames": max(1, round(duration_seconds * fps)),
            "caption_chunks": caption_chunks,
            "audio_path": sanitize_filename(seg.get("audio_path", "")),
            "image_path": sanitize_filename(seg.get("image_path", "")),
        })

    return f"""// Generated by compose_remotion.py

export const CONFIG = {{
  topic: {json.dumps(topic, ensure_ascii=False)},
  aspect: {json.dumps(aspect)},
  width: {width},
  height: {height},
  fps: {fps},
}};

export const BACKGROUNDS = {json.dumps(BACKGROUNDS, indent=2)};

export const SEGMENTS = {json.dumps(slim_segments, indent=2, ensure_ascii=False)};
"""


def ensure_deps() -> bool:
    """Install npm dependencies if node_modules is missing."""
    node_modules = TEMPLATE_DIR / "node_modules"
    if node_modules.is_dir():
        return True
    print(f"Installing npm dependencies in {TEMPLATE_DIR} ...")
    result = subprocess.run(
        ["npm", "install", "--prefer-offline"],
        cwd=str(TEMPLATE_DIR),
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        return False
    return True


def main():
    p = argparse.ArgumentParser(description="Set up Remotion project for rendering")
    p.add_argument("--segments", required=True, help="Path to segments JSON")
    p.add_argument("--topic", required=True, help="Video topic / tag label")
    p.add_argument("--aspect", default="9:16", help="Aspect ratio (default: 9:16)")
    p.add_argument("--fps", type=int, default=30, help="Frames per second (default: 30)")
    p.add_argument("--seg-dur", type=float, default=10.0, help="Duration per segment in seconds (default: 10)")
    args = p.parse_args()

    if not ensure_deps():
        sys.exit(1)

    segments = json.loads(Path(args.segments).read_text(encoding="utf-8"))

    # 1. Generate data.ts
    data_ts = build_data_ts(
        segments=segments,
        topic=args.topic,
        aspect=args.aspect,
        seg_dur=args.seg_dur,
        fps=args.fps,
    )
    (TEMPLATE_DIR / "src" / "data.ts").write_text(data_ts, encoding="utf-8")

    # 2. Generate Root.tsx
    (TEMPLATE_DIR / "src" / "Root.tsx").write_text(ROOT_TSX, encoding="utf-8")

    # 3. Clear and repopulate public/ with current assets
    public_dir = TEMPLATE_DIR / "public"
    if public_dir.is_dir():
        for f in public_dir.iterdir():
            if f.is_file():
                f.unlink()
    else:
        public_dir.mkdir()

    for seg in segments:
        for key in ("audio_path", "image_path"):
            src = seg.get(key, "")
            if src:
                src_path = to_native_path(src)
                if src_path.exists():
                    dst = public_dir / src_path.name
                    if not dst.exists():
                        shutil.copy2(str(src_path), dst)

    print(str(TEMPLATE_DIR.resolve()))


if __name__ == "__main__":
    main()
