// Generated by compose_remotion.py

export const CONFIG = {
  topic: "财联社热点",
  aspect: "9:16",
  width: 1080,
  height: 1920,
  fps: 30,
};

export const BACKGROUNDS = [
  "linear-gradient(180deg, #111111 0%, #1b1b1b 52%, #080808 100%)",
  "linear-gradient(180deg, #101417 0%, #1b2024 52%, #090b0d 100%)",
  "linear-gradient(180deg, #15120f 0%, #211d18 52%, #0b0a08 100%)"
];

export const SEGMENTS = [
  {
    "narration": "科技产业线继续更新。要点是，思科最新报告显示。后续看市场反应。",
    "title": "思科最新研究：全球2000强企业年宕机成本飙升至6000亿美元 两年暴增50%",
    "summary": "思科最新报告显示，全球2000强企业因计划外宕机产生的年度总成本已激增至6000亿美元。",
    "source_label": "财联社",
    "heat_label": "阅读 95,751",
    "category": "科技",
    "score": 95751,
    "comments": 0,
    "duration_seconds": 10.0,
    "duration_frames": 300,
    "caption_chunks": [
      "科技产业线继续更新。",
      "要点是，",
      "思科最新报告显示。",
      "后续看市场反应。"
    ],
    "audio_path": "seg_00.mp3",
    "image_path": "seg_00.png"
  },
  {
    "narration": "盘后消息面继续更新。要点是，爱沙尼亚称北约战机首次在其领空击落无人机。短线看公告反馈。",
    "title": "爱沙尼亚称北约战机首次在其领空击落无人机，乌克兰防长已就此致歉",
    "summary": "爱沙尼亚称北约战机首次在其领空击落无人机，乌克兰防长已就此致歉",
    "source_label": "财联社",
    "heat_label": "阅读 92,075",
    "category": "市场",
    "score": 92075,
    "comments": 0,
    "duration_seconds": 10.0,
    "duration_frames": 300,
    "caption_chunks": [
      "盘后消息面继续更新。",
      "要点是，",
      "爱沙尼亚称北约战机首次在其领空击落无人机。",
      "短线看公告反馈。"
    ],
    "audio_path": "seg_01.mp3",
    "image_path": "seg_01.png"
  },
  {
    "narration": "科技产业线继续更新。要点是，国家数据局印发。相关板块可能继续发酵。",
    "title": "国家数据局：筑牢数字基础设施底座 强化数据赋能人工智能发展",
    "summary": "国家数据局印发《2026年数字经济发展工作要点》。",
    "source_label": "财联社",
    "heat_label": "阅读 83,377",
    "category": "科技",
    "score": 83377,
    "comments": 1,
    "duration_seconds": 10.0,
    "duration_frames": 300,
    "caption_chunks": [
      "科技产业线继续更新。",
      "要点是，",
      "国家数据局印发。",
      "相关板块可能继续发酵。"
    ],
    "audio_path": "seg_02.mp3",
    "image_path": "seg_02.png"
  },
  {
    "narration": "盘后消息面继续更新。要点是，诺和诺德将公布的数据显示。细节披露后影响会更清楚。",
    "title": "诺和诺德将公布的数据显示，旗下司美格鲁肽可应对影响全球约三分之一超重和肥胖人",
    "summary": "诺和诺德将公布的数据显示，旗下司美格鲁肽可应对影响全球约三分之一超重和肥胖人群的肝病危机",
    "source_label": "财联社",
    "heat_label": "阅读 81,388",
    "category": "市场",
    "score": 81388,
    "comments": 0,
    "duration_seconds": 10.0,
    "duration_frames": 300,
    "caption_chunks": [
      "盘后消息面继续更新。",
      "要点是，",
      "诺和诺德将公布的数据显示。",
      "细节披露后影响会更清楚。"
    ],
    "audio_path": "seg_03.mp3",
    "image_path": "seg_03.png"
  },
  {
    "narration": "市场焦点继续切换。要点是，阿塞拜疆国家统计委员会表示。先看情绪，再看交易线索。",
    "title": "阿塞拜疆国家统计委员会表示，1月至4月的石油产量为880万吨，同比下降3.4",
    "summary": "阿塞拜疆国家统计委员会表示，1月至4月的石油产量为880万吨，同比下降3.4%",
    "source_label": "财联社",
    "heat_label": "阅读 76,021",
    "category": "市场",
    "score": 76021,
    "comments": 0,
    "duration_seconds": 10.0,
    "duration_frames": 300,
    "caption_chunks": [
      "市场焦点继续切换。",
      "要点是，",
      "阿塞拜疆国家统计委员会表示。",
      "先看情绪，",
      "再看交易线索。"
    ],
    "audio_path": "seg_04.mp3",
    "image_path": "seg_04.png"
  }
];
