from datetime import datetime
from pathlib import Path

from zen_trader.exceptions import WriteError
from zen_trader.models import ImagePrompt, PlatformContent


def _slugify(text: str, max_len: int = 30) -> str:
    slug = "".join(c if c.isalnum() or c in "._- " else "" for c in text)
    slug = "_".join(slug.split())[:max_len]
    return slug or "content"


def write_content(
    content: PlatformContent,
    output_dir: str | Path,
) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    date_str = datetime.now().strftime("%Y-%m-%d")
    slug = _slugify(content.title)
    filename = f"{content.platform}_{date_str}_{slug}.md"
    filepath = output_dir / filename

    try:
        filepath.write_text(_format_text_output(content), encoding="utf-8")
    except OSError as e:
        raise WriteError(f"Failed to write {filepath}: {e}")

    return filepath


def write_all(
    contents: list[PlatformContent],
    output_dir: str | Path,
) -> list[Path]:
    paths = []
    for c in contents:
        paths.append(write_content(c, output_dir))
    return paths


def write_image_prompt(
    prompt: ImagePrompt,
    output_dir: str | Path,
    platform: str = "common",
) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"{platform}_{date_str}_cover.md"
    filepath = output_dir / filename

    try:
        filepath.write_text(_format_image_output(prompt), encoding="utf-8")
    except OSError as e:
        raise WriteError(f"Failed to write {filepath}: {e}")

    return filepath


def _format_text_output(content: PlatformContent) -> str:
    parts = []
    if content.title:
        parts.append(f"# {content.title}\n")
    parts.append(content.body)
    if content.hashtags:
        parts.append("\n\n" + " ".join(content.hashtags))
    parts.append(f"\n\n---\n*Generated by Zen Trader at {content.generated_at.isoformat()}*")
    return "".join(parts)


def _format_image_output(prompt: ImagePrompt) -> str:
    return f"""# 封面图提示词

> 市场情绪: {prompt.market_sentiment}
> 风格: {prompt.style}
> 生成时间: {datetime.now().isoformat()}

## Midjourney Prompt

```
{prompt.midjourney_prompt}
```

## DALL-E Prompt

```
{prompt.dalle_prompt}
```

## 中文描述

{prompt.description_cn}
"""
